### PR TITLE
Extended and corrected the docstring of `push` concerning the dtype parameter

### PR DESCRIPTION
**Pull request by m-albert**
This is my first PR here 😊 and aims to close https://github.com/clEsperanto/pyclesperanto/issues/151.

### CODE REVIEW

**Comment by StRigaud** [comment]
@m-albert I let you rebase from `main` as I silence the windows CI build for now

**Comment by m-albert** [comment]
@StRigaud Done!

**Review by StRigaud — APPROVED** [review]

**Comment by StRigaud** [comment]
I can merge this or I can wait if you wanna add more things

**Comment by m-albert** [comment]
Feel free to merge, I'd add any further things to a new PR 👍

**Pull request merged**
