### PR TITLE
add notebook showing API changes (function names)

### PR DESCRIPTION
**Pull request by haesleinhuepf**
I'm just adding [a notebook](https://github.com/clEsperanto/pyclesperanto/blob/4fd3203cbba72da8f7035e40c5bf0427be6a77cd/docs/API_differences.ipynb) here so that we could answer questions such as [this one](https://forum.image.sc/t/pyclesperanto-vs-pyclesperanto-prototype/77010/2) easier in the future. 

I could also add a notebook that shows parameter name changes. Does this make sense @StRigaud ? Happy to discuss in an upcoming meeting.

### CODE REVIEW

**Comment by StRigaud** [comment]
HI @haesleinhuepf 

I did a draft PR already for updating the "read the doc" webpage here: https://github.com/clEsperanto/pyclesperanto/pull/173

This introduce one new page to the deployment page of the repo which track the prototype change.
We can also add a notebook for easy testing sure

**Comment by haesleinhuepf** [comment]
ah ok thanks @StRigaud . Do I see it right that #173 contains a manually written documentation, while the notebook here is automatic? I could update it to write the API differences into a .rst file, which could then become part of the website.

**Comment by StRigaud** [comment]
I didn't see properly what the notebook was doing, sorry.

Yes, its a good way to track small changes! I'm in favor. However I would move it to the `demo` folder in the `interoperability` section.
And we should still keep tracks of the modification in the documentations, even if by hand, thats why it is good to have issues :)

**Comment by StRigaud** [comment]
Actually, I think we could integrate the notebool directly in the doc.

I have added a function which look at the difference per `tiers`, to make it easier to read.

**Pull request merged**
